# Source: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbrand-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tbrand-chatbot"
      tier: app
  template:
    metadata:
      labels:
        app: "tbrand-chatbot"
        tier: app
    spec:
      containers:
        - name: tbrand-chatbot
          image: "337390186135.dkr.ecr.ap-northeast-2.amazonaws.com/stg-ecr-golf-aihl:tbrandchatbotv0.0.1"
          imagePullPolicy: Always
          command: ["streamlit", "run", "./tbrand-chatbot/main.py"]
          volumeMounts:
            - name: efs-storage
              mountPath: /DATA/TBrandChatbot
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "512m"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8501
      nodeSelector:
        type: "general"
        sports: 'golf'
        channelID: '1'
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: golf-efs-claim